image_config: &image_config
  IMAGE_NAME: wsl-fidoip
  IMAGE_TAG: 0.1
version: 2
jobs:
  build:
    machine: true
    docker_layer_caching: true
    environment:
      <<: *image_config

    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build --squash -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10
      - store_artifacts:
          path: Dockerfile

workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build:
          context: docker
